spring.application.name=BackendEcomm

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ecomm
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update


Spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fencing.prasad@gmail.com
spring.mail.password=uxeovfzhydsddtfb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true